apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: default
  annotations:
    # Terraform irsa 모듈 outputs.service_role_arns["order"]
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/pposiraegi-eks-order-service-role"
