apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  SPRING_PROFILES_ACTIVE: "prod"
  USER_SERVICE_URL: "http://user-service:8080"
  PRODUCT_SERVICE_URL: "http://product-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8080"
  USER_GRPC_URL: "static://user-service:9090"
  PRODUCT_GRPC_URL: "static://product-service:9090"
  MANAGEMENT_SERVER_PORT: "8081"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  PROMETHEUS_BASE_URL: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://opentelemetry-collector.monitoring.svc.cluster.local:4318/v1/traces"
  LOGGING_PATTERN_CORRELATION: "trace_id=%X{traceId:-} span_id=%X{spanId:-} "
  LOGGING_INCLUDE_APPLICATION_NAME: "false"
