apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: default
  annotations:
    # Terraform irsa 모듈 outputs.service_role_arns["user"]
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/pposiraegi-eks-user-service-role"
