apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  namespace: default
  annotations:
    # Terraform irsa 모듈 outputs.service_role_arns["product"]
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/pposiraegi-eks-product-service-role"
