version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing pnpm...
      - npm install -g pnpm
  pre_build:
    commands:
      - echo Installing dependencies...
      - pnpm install --no-frozen-lockfile
  build:
    commands:
      - echo Building Frontend...
      - pnpm turbo run build --filter=frontend
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync frontend/build s3://$S3_BUCKET --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
      - echo Frontend Deployment completed!
