apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_HOST
    remoteRef:
      key: /pposiraegi/db_host
  - secretKey: DB_USERNAME
    remoteRef:
      key: /pposiraegi/db_username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: /pposiraegi/db_password
  - secretKey: REDIS_HOST
    remoteRef:
      key: /pposiraegi/redis_host
  - secretKey: JWT_SECRET
    remoteRef:
      key: /pposiraegi/jwt_secret
